# Generated by Django 3.2.13 on 2023-12-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0003_usersetting'),
        ('weatherApp', '0004_auto_20231121_2220'),
    ]

    operations = [
    ]
